// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/device_attributes.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InterconnectLink struct {
	DeviceId             int32    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Strength             int32    `protobuf:"varint,3,opt,name=strength,proto3" json:"strength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterconnectLink) Reset()         { *m = InterconnectLink{} }
func (m *InterconnectLink) String() string { return proto.CompactTextString(m) }
func (*InterconnectLink) ProtoMessage()    {}
func (*InterconnectLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_74908851c78ce22e, []int{0}
}

func (m *InterconnectLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterconnectLink.Unmarshal(m, b)
}
func (m *InterconnectLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterconnectLink.Marshal(b, m, deterministic)
}
func (m *InterconnectLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterconnectLink.Merge(m, src)
}
func (m *InterconnectLink) XXX_Size() int {
	return xxx_messageInfo_InterconnectLink.Size(m)
}
func (m *InterconnectLink) XXX_DiscardUnknown() {
	xxx_messageInfo_InterconnectLink.DiscardUnknown(m)
}

var xxx_messageInfo_InterconnectLink proto.InternalMessageInfo

func (m *InterconnectLink) GetDeviceId() int32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *InterconnectLink) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InterconnectLink) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type LocalLinks struct {
	Link                 []*InterconnectLink `protobuf:"bytes,1,rep,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LocalLinks) Reset()         { *m = LocalLinks{} }
func (m *LocalLinks) String() string { return proto.CompactTextString(m) }
func (*LocalLinks) ProtoMessage()    {}
func (*LocalLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_74908851c78ce22e, []int{1}
}

func (m *LocalLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalLinks.Unmarshal(m, b)
}
func (m *LocalLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalLinks.Marshal(b, m, deterministic)
}
func (m *LocalLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalLinks.Merge(m, src)
}
func (m *LocalLinks) XXX_Size() int {
	return xxx_messageInfo_LocalLinks.Size(m)
}
func (m *LocalLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalLinks.DiscardUnknown(m)
}

var xxx_messageInfo_LocalLinks proto.InternalMessageInfo

func (m *LocalLinks) GetLink() []*InterconnectLink {
	if m != nil {
		return m.Link
	}
	return nil
}

type DeviceLocality struct {
	// Optional bus locality of device.  Default value of 0 means
	// no specific locality.  Specific localities are indexed from 1.
	BusId int32 `protobuf:"varint,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	// Optional NUMA locality of device.
	NumaNode int32 `protobuf:"varint,2,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	// Optional local interconnect links to other devices.
	Links                *LocalLinks `protobuf:"bytes,3,opt,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeviceLocality) Reset()         { *m = DeviceLocality{} }
func (m *DeviceLocality) String() string { return proto.CompactTextString(m) }
func (*DeviceLocality) ProtoMessage()    {}
func (*DeviceLocality) Descriptor() ([]byte, []int) {
	return fileDescriptor_74908851c78ce22e, []int{2}
}

func (m *DeviceLocality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceLocality.Unmarshal(m, b)
}
func (m *DeviceLocality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceLocality.Marshal(b, m, deterministic)
}
func (m *DeviceLocality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceLocality.Merge(m, src)
}
func (m *DeviceLocality) XXX_Size() int {
	return xxx_messageInfo_DeviceLocality.Size(m)
}
func (m *DeviceLocality) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceLocality.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceLocality proto.InternalMessageInfo

func (m *DeviceLocality) GetBusId() int32 {
	if m != nil {
		return m.BusId
	}
	return 0
}

func (m *DeviceLocality) GetNumaNode() int32 {
	if m != nil {
		return m.NumaNode
	}
	return 0
}

func (m *DeviceLocality) GetLinks() *LocalLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

type DeviceAttributes struct {
	// Fully specified name of the device within a cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// String representation of device_type.
	DeviceType string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// Memory capacity of device in bytes.
	MemoryLimit int64 `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	// Platform-specific data about device that may be useful
	// for supporting efficient data transfers.
	Locality *DeviceLocality `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	// A device is assigned a global unique number each time it is
	// initialized. "incarnation" should never be 0.
	Incarnation uint64 `protobuf:"fixed64,6,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// String representation of the physical device that this device maps to.
	PhysicalDeviceDesc   string   `protobuf:"bytes,7,opt,name=physical_device_desc,json=physicalDeviceDesc,proto3" json:"physical_device_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceAttributes) Reset()         { *m = DeviceAttributes{} }
func (m *DeviceAttributes) String() string { return proto.CompactTextString(m) }
func (*DeviceAttributes) ProtoMessage()    {}
func (*DeviceAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_74908851c78ce22e, []int{3}
}

func (m *DeviceAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceAttributes.Unmarshal(m, b)
}
func (m *DeviceAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceAttributes.Marshal(b, m, deterministic)
}
func (m *DeviceAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceAttributes.Merge(m, src)
}
func (m *DeviceAttributes) XXX_Size() int {
	return xxx_messageInfo_DeviceAttributes.Size(m)
}
func (m *DeviceAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceAttributes proto.InternalMessageInfo

func (m *DeviceAttributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceAttributes) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceAttributes) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *DeviceAttributes) GetLocality() *DeviceLocality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *DeviceAttributes) GetIncarnation() uint64 {
	if m != nil {
		return m.Incarnation
	}
	return 0
}

func (m *DeviceAttributes) GetPhysicalDeviceDesc() string {
	if m != nil {
		return m.PhysicalDeviceDesc
	}
	return ""
}

func init() {
	proto.RegisterType((*InterconnectLink)(nil), "tensorflow.InterconnectLink")
	proto.RegisterType((*LocalLinks)(nil), "tensorflow.LocalLinks")
	proto.RegisterType((*DeviceLocality)(nil), "tensorflow.DeviceLocality")
	proto.RegisterType((*DeviceAttributes)(nil), "tensorflow.DeviceAttributes")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/device_attributes.proto", fileDescriptor_74908851c78ce22e)
}

var fileDescriptor_74908851c78ce22e = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6b, 0xdb, 0x30,
	0x14, 0xc6, 0xd1, 0x12, 0x67, 0xc9, 0xf3, 0x18, 0x45, 0x6c, 0x45, 0x74, 0x83, 0x79, 0x39, 0xf9,
	0xb0, 0xc6, 0x5d, 0x07, 0x3b, 0x0e, 0x5a, 0x7a, 0x09, 0x84, 0x51, 0xc4, 0x4e, 0xbb, 0x18, 0x59,
	0x56, 0x13, 0x11, 0x5b, 0x2f, 0x48, 0xf2, 0x4a, 0xf6, 0x87, 0x8f, 0x1d, 0x87, 0xe5, 0x34, 0xf6,
	0x02, 0xbd, 0xc9, 0x9f, 0x3f, 0xbd, 0xef, 0xa7, 0x8f, 0x07, 0x9f, 0xbd, 0x32, 0x0e, 0xed, 0x43,
	0x85, 0x8f, 0x99, 0x44, 0xab, 0xb2, 0x07, 0x2b, 0x6a, 0xf5, 0x88, 0x76, 0x9b, 0x95, 0xea, 0x97,
	0x96, 0x2a, 0x17, 0xde, 0x5b, 0x5d, 0x34, 0x5e, 0xb9, 0xc5, 0xce, 0xa2, 0x47, 0x0a, 0xfd, 0x95,
	0x79, 0x0e, 0x67, 0x4b, 0xe3, 0x95, 0x95, 0x68, 0x8c, 0x92, 0x7e, 0xa5, 0xcd, 0x96, 0xbe, 0x83,
	0xd9, 0xe1, 0xaa, 0x2e, 0x19, 0x49, 0x48, 0x1a, 0xf1, 0x69, 0x27, 0x2c, 0x4b, 0x4a, 0x61, 0xec,
	0xf7, 0x3b, 0xc5, 0x5e, 0x24, 0x24, 0x9d, 0xf1, 0x70, 0xa6, 0x17, 0x30, 0x75, 0xde, 0x2a, 0xb3,
	0xf6, 0x1b, 0x36, 0xea, 0xfc, 0x4f, 0xdf, 0xf3, 0x6f, 0x00, 0x2b, 0x94, 0xa2, 0x6a, 0x27, 0x3b,
	0x7a, 0x05, 0xe3, 0x4a, 0x9b, 0x2d, 0x23, 0xc9, 0x28, 0x8d, 0xaf, 0xdf, 0x2f, 0x7a, 0x92, 0xc5,
	0x29, 0x06, 0x0f, 0xce, 0xb9, 0x85, 0xd7, 0x77, 0x21, 0x3b, 0x4c, 0xd1, 0x7e, 0x4f, 0xdf, 0xc2,
	0xa4, 0x68, 0x5c, 0xcf, 0x16, 0x15, 0x8d, 0x5b, 0x96, 0x2d, 0xb5, 0x69, 0x6a, 0x91, 0x1b, 0x2c,
	0x3b, 0xba, 0x88, 0x4f, 0x5b, 0xe1, 0x3b, 0x96, 0x8a, 0x7e, 0x82, 0xa8, 0x9d, 0xe6, 0x02, 0x5e,
	0x7c, 0x7d, 0x3e, 0x0c, 0xee, 0xf1, 0x78, 0x67, 0x9a, 0xff, 0x21, 0x70, 0xd6, 0x85, 0xde, 0x1c,
	0xbb, 0x6b, 0x1f, 0x6e, 0x44, 0xad, 0x42, 0xe8, 0x8c, 0x87, 0x33, 0xfd, 0x00, 0xf1, 0xa1, 0xa9,
	0x41, 0x27, 0xd0, 0x49, 0x3f, 0xda, 0x66, 0x3e, 0xc2, 0xab, 0x5a, 0xd5, 0x68, 0xf7, 0x79, 0xa5,
	0x6b, 0xed, 0xd9, 0x38, 0x21, 0xe9, 0x88, 0xc7, 0x9d, 0xb6, 0x6a, 0x25, 0xfa, 0x15, 0xa6, 0xd5,
	0xe1, 0x69, 0x2c, 0x0a, 0x74, 0x17, 0x43, 0xba, 0xff, 0x1f, 0xcf, 0x8f, 0x5e, 0x9a, 0x40, 0xac,
	0x8d, 0x14, 0xd6, 0x08, 0xaf, 0xd1, 0xb0, 0x49, 0x42, 0xd2, 0x09, 0x1f, 0x4a, 0xf4, 0x0a, 0xde,
	0xec, 0x36, 0x7b, 0xa7, 0xa5, 0xa8, 0xf2, 0x03, 0x66, 0xa9, 0x9c, 0x64, 0x2f, 0x03, 0x26, 0x7d,
	0xfa, 0xd7, 0x25, 0xdc, 0x29, 0x27, 0x6f, 0x7f, 0x03, 0x43, 0xbb, 0x1e, 0xc6, 0x1f, 0xb7, 0xe9,
	0xf6, 0xfc, 0xb4, 0x91, 0xfb, 0x76, 0x99, 0xdc, 0x3d, 0xf9, 0x79, 0xb3, 0xd6, 0x7e, 0xd3, 0x14,
	0x0b, 0x89, 0x75, 0xe6, 0x71, 0x87, 0xee, 0x52, 0xe8, 0xac, 0x9f, 0x71, 0x19, 0xb6, 0x2e, 0x5b,
	0x63, 0xf6, 0xec, 0xaa, 0xfe, 0x25, 0xa4, 0x98, 0x04, 0xdb, 0x97, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x7e, 0x56, 0xe3, 0xd1, 0x02, 0x00, 0x00,
}
