// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/function.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A library is a set of named functions.
type FunctionDefLibrary struct {
	Function             []*FunctionDef `protobuf:"bytes,1,rep,name=function,proto3" json:"function,omitempty"`
	Gradient             []*GradientDef `protobuf:"bytes,2,rep,name=gradient,proto3" json:"gradient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FunctionDefLibrary) Reset()         { *m = FunctionDefLibrary{} }
func (m *FunctionDefLibrary) String() string { return proto.CompactTextString(m) }
func (*FunctionDefLibrary) ProtoMessage()    {}
func (*FunctionDefLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_507748d6812c5f14, []int{0}
}

func (m *FunctionDefLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionDefLibrary.Unmarshal(m, b)
}
func (m *FunctionDefLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionDefLibrary.Marshal(b, m, deterministic)
}
func (m *FunctionDefLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionDefLibrary.Merge(m, src)
}
func (m *FunctionDefLibrary) XXX_Size() int {
	return xxx_messageInfo_FunctionDefLibrary.Size(m)
}
func (m *FunctionDefLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionDefLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionDefLibrary proto.InternalMessageInfo

func (m *FunctionDefLibrary) GetFunction() []*FunctionDef {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *FunctionDefLibrary) GetGradient() []*GradientDef {
	if m != nil {
		return m.Gradient
	}
	return nil
}

// A function can be instantiated when the runtime can bind every attr
// with a value. When a GraphDef has a call to a function, it must
// have binding for every attr defined in the signature.
//
// TODO(zhifengc):
//   * device spec, etc.
type FunctionDef struct {
	// The definition of the function's name, arguments, return values,
	// attrs etc.
	Signature *OpDef `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Attributes specific to this function definition.
	Attr    map[string]*AttrValue            `protobuf:"bytes,5,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ArgAttr map[uint32]*FunctionDef_ArgAttrs `protobuf:"bytes,7,rep,name=arg_attr,json=argAttr,proto3" json:"arg_attr,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// By convention, "op" in node_def is resolved by consulting with a
	// user-defined library first. If not resolved, "func" is assumed to
	// be a builtin op.
	NodeDef []*NodeDef `protobuf:"bytes,3,rep,name=node_def,json=nodeDef,proto3" json:"node_def,omitempty"`
	// A mapping from the output arg names from `signature` to the
	// outputs from `node_def` that should be returned by the function.
	Ret map[string]string `protobuf:"bytes,4,rep,name=ret,proto3" json:"ret,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// A mapping from control output names from `signature` to node names in
	// `node_def` which should be control outputs of this function.
	ControlRet           map[string]string `protobuf:"bytes,6,rep,name=control_ret,json=controlRet,proto3" json:"control_ret,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FunctionDef) Reset()         { *m = FunctionDef{} }
func (m *FunctionDef) String() string { return proto.CompactTextString(m) }
func (*FunctionDef) ProtoMessage()    {}
func (*FunctionDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_507748d6812c5f14, []int{1}
}

func (m *FunctionDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionDef.Unmarshal(m, b)
}
func (m *FunctionDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionDef.Marshal(b, m, deterministic)
}
func (m *FunctionDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionDef.Merge(m, src)
}
func (m *FunctionDef) XXX_Size() int {
	return xxx_messageInfo_FunctionDef.Size(m)
}
func (m *FunctionDef) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionDef.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionDef proto.InternalMessageInfo

func (m *FunctionDef) GetSignature() *OpDef {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *FunctionDef) GetAttr() map[string]*AttrValue {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *FunctionDef) GetArgAttr() map[uint32]*FunctionDef_ArgAttrs {
	if m != nil {
		return m.ArgAttr
	}
	return nil
}

func (m *FunctionDef) GetNodeDef() []*NodeDef {
	if m != nil {
		return m.NodeDef
	}
	return nil
}

func (m *FunctionDef) GetRet() map[string]string {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FunctionDef) GetControlRet() map[string]string {
	if m != nil {
		return m.ControlRet
	}
	return nil
}

// Attributes for function arguments. These attributes are the same set of
// valid attributes as to _Arg nodes.
type FunctionDef_ArgAttrs struct {
	Attr                 map[string]*AttrValue `protobuf:"bytes,1,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FunctionDef_ArgAttrs) Reset()         { *m = FunctionDef_ArgAttrs{} }
func (m *FunctionDef_ArgAttrs) String() string { return proto.CompactTextString(m) }
func (*FunctionDef_ArgAttrs) ProtoMessage()    {}
func (*FunctionDef_ArgAttrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_507748d6812c5f14, []int{1, 1}
}

func (m *FunctionDef_ArgAttrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionDef_ArgAttrs.Unmarshal(m, b)
}
func (m *FunctionDef_ArgAttrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionDef_ArgAttrs.Marshal(b, m, deterministic)
}
func (m *FunctionDef_ArgAttrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionDef_ArgAttrs.Merge(m, src)
}
func (m *FunctionDef_ArgAttrs) XXX_Size() int {
	return xxx_messageInfo_FunctionDef_ArgAttrs.Size(m)
}
func (m *FunctionDef_ArgAttrs) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionDef_ArgAttrs.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionDef_ArgAttrs proto.InternalMessageInfo

func (m *FunctionDef_ArgAttrs) GetAttr() map[string]*AttrValue {
	if m != nil {
		return m.Attr
	}
	return nil
}

// GradientDef defines the gradient function of a function defined in
// a function library.
//
// A gradient function g (specified by gradient_func) for a function f
// (specified by function_name) must follow the following:
//
// The function 'f' must be a numerical function which takes N inputs
// and produces M outputs. Its gradient function 'g', which is a
// function taking N + M inputs and produces N outputs.
//
// I.e. if we have
//    (y1, y2, ..., y_M) = f(x1, x2, ..., x_N),
// then, g is
//    (dL/dx1, dL/dx2, ..., dL/dx_N) = g(x1, x2, ..., x_N,
//                                      dL/dy1, dL/dy2, ..., dL/dy_M),
// where L is a scalar-value function of (x1, x2, ..., xN) (e.g., the
// loss function). dL/dx_i is the partial derivative of L with respect
// to x_i.
type GradientDef struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	GradientFunc         string   `protobuf:"bytes,2,opt,name=gradient_func,json=gradientFunc,proto3" json:"gradient_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradientDef) Reset()         { *m = GradientDef{} }
func (m *GradientDef) String() string { return proto.CompactTextString(m) }
func (*GradientDef) ProtoMessage()    {}
func (*GradientDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_507748d6812c5f14, []int{2}
}

func (m *GradientDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradientDef.Unmarshal(m, b)
}
func (m *GradientDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradientDef.Marshal(b, m, deterministic)
}
func (m *GradientDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradientDef.Merge(m, src)
}
func (m *GradientDef) XXX_Size() int {
	return xxx_messageInfo_GradientDef.Size(m)
}
func (m *GradientDef) XXX_DiscardUnknown() {
	xxx_messageInfo_GradientDef.DiscardUnknown(m)
}

var xxx_messageInfo_GradientDef proto.InternalMessageInfo

func (m *GradientDef) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *GradientDef) GetGradientFunc() string {
	if m != nil {
		return m.GradientFunc
	}
	return ""
}

func init() {
	proto.RegisterType((*FunctionDefLibrary)(nil), "tensorflow.FunctionDefLibrary")
	proto.RegisterType((*FunctionDef)(nil), "tensorflow.FunctionDef")
	proto.RegisterMapType((map[uint32]*FunctionDef_ArgAttrs)(nil), "tensorflow.FunctionDef.ArgAttrEntry")
	proto.RegisterMapType((map[string]*AttrValue)(nil), "tensorflow.FunctionDef.AttrEntry")
	proto.RegisterMapType((map[string]string)(nil), "tensorflow.FunctionDef.ControlRetEntry")
	proto.RegisterMapType((map[string]string)(nil), "tensorflow.FunctionDef.RetEntry")
	proto.RegisterType((*FunctionDef_ArgAttrs)(nil), "tensorflow.FunctionDef.ArgAttrs")
	proto.RegisterMapType((map[string]*AttrValue)(nil), "tensorflow.FunctionDef.ArgAttrs.AttrEntry")
	proto.RegisterType((*GradientDef)(nil), "tensorflow.GradientDef")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/function.proto", fileDescriptor_507748d6812c5f14)
}

var fileDescriptor_507748d6812c5f14 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0xd3, 0x6d, 0xd3, 0x93, 0xae, 0xae, 0xa3, 0x62, 0xe8, 0x55, 0xad, 0xa2, 0x65,
	0x65, 0x13, 0xe8, 0xe2, 0x22, 0x82, 0xca, 0xae, 0x7f, 0x11, 0xa9, 0x4b, 0x2e, 0x14, 0x44, 0x08,
	0xd3, 0x74, 0x12, 0xc3, 0xb6, 0x33, 0x65, 0x32, 0x75, 0xe9, 0x8d, 0x0f, 0xe2, 0x33, 0xf8, 0x80,
	0x5e, 0xca, 0x4c, 0x32, 0xc9, 0xb8, 0x1a, 0x8b, 0xb0, 0x77, 0xc9, 0xcc, 0xf7, 0xfb, 0xce, 0xc9,
	0x37, 0x99, 0x03, 0x63, 0x41, 0x68, 0xce, 0x78, 0xb2, 0x60, 0xe7, 0x41, 0xcc, 0x38, 0x09, 0x12,
	0x8e, 0x97, 0xe4, 0x9c, 0xf1, 0xb3, 0x20, 0x59, 0xd3, 0x58, 0x64, 0x8c, 0xfa, 0x2b, 0xce, 0x04,
	0x43, 0x50, 0x2b, 0x07, 0xfb, 0xcd, 0x14, 0x16, 0x82, 0x47, 0x5f, 0xf1, 0x62, 0x4d, 0x0a, 0x6e,
	0xf0, 0x8f, 0x0a, 0x94, 0xcd, 0x49, 0x34, 0x27, 0x49, 0xa9, 0xbc, 0xd7, 0xac, 0x64, 0xab, 0x5a,
	0x37, 0xfa, 0x06, 0xe8, 0x55, 0xd9, 0xdb, 0x0b, 0x92, 0xbc, 0xcb, 0x66, 0x1c, 0xf3, 0x0d, 0x3a,
	0x04, 0x47, 0x77, 0xec, 0x59, 0x43, 0x7b, 0xec, 0x4e, 0x6e, 0xf9, 0xb5, 0xa1, 0x6f, 0x10, 0x61,
	0x25, 0x94, 0x50, 0xca, 0xf1, 0x3c, 0x23, 0x54, 0x78, 0xad, 0x3f, 0xa1, 0xd7, 0xe5, 0x9e, 0x82,
	0xb4, 0x70, 0xf4, 0xa3, 0x03, 0xae, 0x61, 0x87, 0x02, 0xe8, 0xe5, 0x59, 0x4a, 0xb1, 0x58, 0x73,
	0xe2, 0x59, 0x43, 0x6b, 0xec, 0x4e, 0xae, 0x99, 0x2e, 0xef, 0x57, 0x92, 0xaf, 0x35, 0xe8, 0x21,
	0xb4, 0x65, 0x4c, 0xde, 0x8e, 0xaa, 0x78, 0xbb, 0xa1, 0x4d, 0xff, 0x58, 0x08, 0xfe, 0x92, 0x0a,
	0xbe, 0x09, 0x95, 0x1c, 0x3d, 0x03, 0x07, 0xf3, 0x34, 0x52, 0x68, 0x57, 0xa1, 0x77, 0x1b, 0x51,
	0x9e, 0xd6, 0x74, 0x17, 0x17, 0x6f, 0xc8, 0x07, 0x47, 0x47, 0xee, 0xd9, 0xca, 0xe0, 0xba, 0x69,
	0x30, 0x65, 0x73, 0x22, 0x3b, 0xed, 0xd2, 0xe2, 0x01, 0x4d, 0xc0, 0xe6, 0x44, 0x78, 0x6d, 0x25,
	0x1d, 0x36, 0xd5, 0x0a, 0x89, 0x28, 0xea, 0x48, 0x31, 0x7a, 0x03, 0x6e, 0xcc, 0xa8, 0xe0, 0x6c,
	0x11, 0x49, 0xb6, 0xa3, 0xd8, 0xfb, 0x4d, 0xec, 0xf3, 0x42, 0x5a, 0x59, 0x40, 0x5c, 0x2d, 0x0c,
	0xa6, 0xd0, 0xab, 0xbe, 0x01, 0xed, 0x81, 0x7d, 0x46, 0x36, 0x2a, 0xdd, 0x5e, 0x28, 0x1f, 0xd1,
	0x03, 0xd8, 0x51, 0xbf, 0x99, 0xd7, 0x52, 0x89, 0xdf, 0x34, 0x4b, 0x48, 0xee, 0x83, 0xdc, 0x0c,
	0x0b, 0xcd, 0xe3, 0xd6, 0x23, 0x6b, 0xf0, 0xdd, 0x02, 0xa7, 0xcc, 0x25, 0x47, 0x4f, 0xcb, 0x23,
	0x28, 0xfe, 0x94, 0xfd, 0x2d, 0x39, 0xe6, 0x17, 0xcf, 0xe2, 0xd2, 0x9b, 0xfb, 0x0c, 0x7d, 0xf3,
	0xcc, 0x4c, 0xcb, 0xdd, 0xc2, 0xf2, 0xe8, 0x77, 0xcb, 0xe1, 0xb6, 0x96, 0x4d, 0xf7, 0x23, 0x70,
	0x74, 0xc4, 0x7f, 0x69, 0xf6, 0x86, 0xe9, 0xdc, 0x33, 0xb9, 0x27, 0x70, 0xf5, 0xc2, 0x09, 0xfd,
	0x0f, 0xfe, 0xb6, 0xed, 0xb4, 0xf6, 0xec, 0xd1, 0x47, 0x70, 0x8d, 0x7b, 0x84, 0xee, 0xc0, 0xae,
	0xbe, 0x7e, 0x11, 0xc5, 0x4b, 0x52, 0x5a, 0xf5, 0xf5, 0xe2, 0x14, 0x2f, 0x89, 0x14, 0xe9, 0xeb,
	0x16, 0xc9, 0x8d, 0xd2, 0xbb, 0xaf, 0x17, 0xe5, 0x07, 0x9f, 0x70, 0xf0, 0x18, 0x4f, 0xcd, 0x1c,
	0xaa, 0x81, 0x71, 0x72, 0x45, 0x47, 0x72, 0x2a, 0x47, 0x46, 0x7e, 0x6a, 0x7d, 0x3a, 0x4e, 0x33,
	0xf1, 0x65, 0x3d, 0xf3, 0x63, 0xb6, 0x0c, 0x04, 0x5b, 0xb1, 0xfc, 0x00, 0x67, 0x41, 0xcd, 0x1e,
	0xa8, 0xd9, 0x12, 0xa4, 0x2c, 0x68, 0x9c, 0x42, 0x3f, 0x2d, 0x6b, 0xd6, 0x51, 0xb2, 0xc3, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x95, 0x46, 0xf3, 0x38, 0x05, 0x00, 0x00,
}
