// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/graph_transfer_info.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphTransferInfo_Destination int32

const (
	GraphTransferInfo_NOP     GraphTransferInfo_Destination = 0
	GraphTransferInfo_HEXAGON GraphTransferInfo_Destination = 1
)

var GraphTransferInfo_Destination_name = map[int32]string{
	0: "NOP",
	1: "HEXAGON",
}

var GraphTransferInfo_Destination_value = map[string]int32{
	"NOP":     0,
	"HEXAGON": 1,
}

func (x GraphTransferInfo_Destination) String() string {
	return proto.EnumName(GraphTransferInfo_Destination_name, int32(x))
}

func (GraphTransferInfo_Destination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{7, 0}
}

type GraphTransferNodeInput struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OutputPort           int32    `protobuf:"varint,2,opt,name=output_port,json=outputPort,proto3" json:"output_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferNodeInput) Reset()         { *m = GraphTransferNodeInput{} }
func (m *GraphTransferNodeInput) String() string { return proto.CompactTextString(m) }
func (*GraphTransferNodeInput) ProtoMessage()    {}
func (*GraphTransferNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{0}
}

func (m *GraphTransferNodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferNodeInput.Unmarshal(m, b)
}
func (m *GraphTransferNodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferNodeInput.Marshal(b, m, deterministic)
}
func (m *GraphTransferNodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferNodeInput.Merge(m, src)
}
func (m *GraphTransferNodeInput) XXX_Size() int {
	return xxx_messageInfo_GraphTransferNodeInput.Size(m)
}
func (m *GraphTransferNodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferNodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferNodeInput proto.InternalMessageInfo

func (m *GraphTransferNodeInput) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInput) GetOutputPort() int32 {
	if m != nil {
		return m.OutputPort
	}
	return 0
}

type GraphTransferNodeInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeId               int32    `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TypeName             string   `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	SocOpId              int32    `protobuf:"varint,4,opt,name=soc_op_id,json=socOpId,proto3" json:"soc_op_id,omitempty"`
	PaddingId            int32    `protobuf:"varint,5,opt,name=padding_id,json=paddingId,proto3" json:"padding_id,omitempty"`
	InputCount           int32    `protobuf:"varint,6,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	OutputCount          int32    `protobuf:"varint,7,opt,name=output_count,json=outputCount,proto3" json:"output_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferNodeInfo) Reset()         { *m = GraphTransferNodeInfo{} }
func (m *GraphTransferNodeInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferNodeInfo) ProtoMessage()    {}
func (*GraphTransferNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{1}
}

func (m *GraphTransferNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferNodeInfo.Unmarshal(m, b)
}
func (m *GraphTransferNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferNodeInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferNodeInfo.Merge(m, src)
}
func (m *GraphTransferNodeInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferNodeInfo.Size(m)
}
func (m *GraphTransferNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferNodeInfo proto.InternalMessageInfo

func (m *GraphTransferNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferNodeInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *GraphTransferNodeInfo) GetSocOpId() int32 {
	if m != nil {
		return m.SocOpId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetPaddingId() int32 {
	if m != nil {
		return m.PaddingId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetInputCount() int32 {
	if m != nil {
		return m.InputCount
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetOutputCount() int32 {
	if m != nil {
		return m.OutputCount
	}
	return 0
}

type GraphTransferConstNodeInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeId               int32    `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Shape                []int64  `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Dtype                DataType `protobuf:"varint,5,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferConstNodeInfo) Reset()         { *m = GraphTransferConstNodeInfo{} }
func (m *GraphTransferConstNodeInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferConstNodeInfo) ProtoMessage()    {}
func (*GraphTransferConstNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{2}
}

func (m *GraphTransferConstNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferConstNodeInfo.Unmarshal(m, b)
}
func (m *GraphTransferConstNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferConstNodeInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferConstNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferConstNodeInfo.Merge(m, src)
}
func (m *GraphTransferConstNodeInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferConstNodeInfo.Size(m)
}
func (m *GraphTransferConstNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferConstNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferConstNodeInfo proto.InternalMessageInfo

func (m *GraphTransferConstNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferConstNodeInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferConstNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferConstNodeInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GraphTransferConstNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DataType_DT_INVALID
}

type GraphTransferNodeInputInfo struct {
	NodeId               int32                     `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeInput            []*GraphTransferNodeInput `protobuf:"bytes,2,rep,name=node_input,json=nodeInput,proto3" json:"node_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GraphTransferNodeInputInfo) Reset()         { *m = GraphTransferNodeInputInfo{} }
func (m *GraphTransferNodeInputInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferNodeInputInfo) ProtoMessage()    {}
func (*GraphTransferNodeInputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{3}
}

func (m *GraphTransferNodeInputInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferNodeInputInfo.Unmarshal(m, b)
}
func (m *GraphTransferNodeInputInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferNodeInputInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferNodeInputInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferNodeInputInfo.Merge(m, src)
}
func (m *GraphTransferNodeInputInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferNodeInputInfo.Size(m)
}
func (m *GraphTransferNodeInputInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferNodeInputInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferNodeInputInfo proto.InternalMessageInfo

func (m *GraphTransferNodeInputInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInputInfo) GetNodeInput() []*GraphTransferNodeInput {
	if m != nil {
		return m.NodeInput
	}
	return nil
}

type GraphTransferNodeOutputInfo struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MaxByteSize          []int32  `protobuf:"varint,2,rep,packed,name=max_byte_size,json=maxByteSize,proto3" json:"max_byte_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferNodeOutputInfo) Reset()         { *m = GraphTransferNodeOutputInfo{} }
func (m *GraphTransferNodeOutputInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferNodeOutputInfo) ProtoMessage()    {}
func (*GraphTransferNodeOutputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{4}
}

func (m *GraphTransferNodeOutputInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferNodeOutputInfo.Unmarshal(m, b)
}
func (m *GraphTransferNodeOutputInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferNodeOutputInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferNodeOutputInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferNodeOutputInfo.Merge(m, src)
}
func (m *GraphTransferNodeOutputInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferNodeOutputInfo.Size(m)
}
func (m *GraphTransferNodeOutputInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferNodeOutputInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferNodeOutputInfo proto.InternalMessageInfo

func (m *GraphTransferNodeOutputInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeOutputInfo) GetMaxByteSize() []int32 {
	if m != nil {
		return m.MaxByteSize
	}
	return nil
}

type GraphTransferGraphInputNodeInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape                []int64  `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Dtype                DataType `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferGraphInputNodeInfo) Reset()         { *m = GraphTransferGraphInputNodeInfo{} }
func (m *GraphTransferGraphInputNodeInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferGraphInputNodeInfo) ProtoMessage()    {}
func (*GraphTransferGraphInputNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{5}
}

func (m *GraphTransferGraphInputNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferGraphInputNodeInfo.Unmarshal(m, b)
}
func (m *GraphTransferGraphInputNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferGraphInputNodeInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferGraphInputNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferGraphInputNodeInfo.Merge(m, src)
}
func (m *GraphTransferGraphInputNodeInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferGraphInputNodeInfo.Size(m)
}
func (m *GraphTransferGraphInputNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferGraphInputNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferGraphInputNodeInfo proto.InternalMessageInfo

func (m *GraphTransferGraphInputNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferGraphInputNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferGraphInputNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DataType_DT_INVALID
}

type GraphTransferGraphOutputNodeInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape                []int64  `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Dtype                DataType `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphTransferGraphOutputNodeInfo) Reset()         { *m = GraphTransferGraphOutputNodeInfo{} }
func (m *GraphTransferGraphOutputNodeInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferGraphOutputNodeInfo) ProtoMessage()    {}
func (*GraphTransferGraphOutputNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{6}
}

func (m *GraphTransferGraphOutputNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferGraphOutputNodeInfo.Unmarshal(m, b)
}
func (m *GraphTransferGraphOutputNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferGraphOutputNodeInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferGraphOutputNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferGraphOutputNodeInfo.Merge(m, src)
}
func (m *GraphTransferGraphOutputNodeInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferGraphOutputNodeInfo.Size(m)
}
func (m *GraphTransferGraphOutputNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferGraphOutputNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferGraphOutputNodeInfo proto.InternalMessageInfo

func (m *GraphTransferGraphOutputNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferGraphOutputNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferGraphOutputNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DataType_DT_INVALID
}

// Protocol buffer representing a handle to a tensorflow resource. Handles are
// not valid across executions, but can be serialized back and forth from within
// a single run.
type GraphTransferInfo struct {
	NodeInfo       []*GraphTransferNodeInfo       `protobuf:"bytes,1,rep,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	ConstNodeInfo  []*GraphTransferConstNodeInfo  `protobuf:"bytes,2,rep,name=const_node_info,json=constNodeInfo,proto3" json:"const_node_info,omitempty"`
	NodeInputInfo  []*GraphTransferNodeInputInfo  `protobuf:"bytes,3,rep,name=node_input_info,json=nodeInputInfo,proto3" json:"node_input_info,omitempty"`
	NodeOutputInfo []*GraphTransferNodeOutputInfo `protobuf:"bytes,4,rep,name=node_output_info,json=nodeOutputInfo,proto3" json:"node_output_info,omitempty"`
	// Input Node parameters of transferred graph
	GraphInputNodeInfo  []*GraphTransferGraphInputNodeInfo  `protobuf:"bytes,5,rep,name=graph_input_node_info,json=graphInputNodeInfo,proto3" json:"graph_input_node_info,omitempty"`
	GraphOutputNodeInfo []*GraphTransferGraphOutputNodeInfo `protobuf:"bytes,6,rep,name=graph_output_node_info,json=graphOutputNodeInfo,proto3" json:"graph_output_node_info,omitempty"`
	// Destination of graph transfer
	Destination          GraphTransferInfo_Destination `protobuf:"varint,7,opt,name=destination,proto3,enum=tensorflow.GraphTransferInfo_Destination" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GraphTransferInfo) Reset()         { *m = GraphTransferInfo{} }
func (m *GraphTransferInfo) String() string { return proto.CompactTextString(m) }
func (*GraphTransferInfo) ProtoMessage()    {}
func (*GraphTransferInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3a1e773f26c9475, []int{7}
}

func (m *GraphTransferInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphTransferInfo.Unmarshal(m, b)
}
func (m *GraphTransferInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphTransferInfo.Marshal(b, m, deterministic)
}
func (m *GraphTransferInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphTransferInfo.Merge(m, src)
}
func (m *GraphTransferInfo) XXX_Size() int {
	return xxx_messageInfo_GraphTransferInfo.Size(m)
}
func (m *GraphTransferInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphTransferInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphTransferInfo proto.InternalMessageInfo

func (m *GraphTransferInfo) GetNodeInfo() []*GraphTransferNodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetConstNodeInfo() []*GraphTransferConstNodeInfo {
	if m != nil {
		return m.ConstNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetNodeInputInfo() []*GraphTransferNodeInputInfo {
	if m != nil {
		return m.NodeInputInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetNodeOutputInfo() []*GraphTransferNodeOutputInfo {
	if m != nil {
		return m.NodeOutputInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetGraphInputNodeInfo() []*GraphTransferGraphInputNodeInfo {
	if m != nil {
		return m.GraphInputNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetGraphOutputNodeInfo() []*GraphTransferGraphOutputNodeInfo {
	if m != nil {
		return m.GraphOutputNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetDestination() GraphTransferInfo_Destination {
	if m != nil {
		return m.Destination
	}
	return GraphTransferInfo_NOP
}

func init() {
	proto.RegisterEnum("tensorflow.GraphTransferInfo_Destination", GraphTransferInfo_Destination_name, GraphTransferInfo_Destination_value)
	proto.RegisterType((*GraphTransferNodeInput)(nil), "tensorflow.GraphTransferNodeInput")
	proto.RegisterType((*GraphTransferNodeInfo)(nil), "tensorflow.GraphTransferNodeInfo")
	proto.RegisterType((*GraphTransferConstNodeInfo)(nil), "tensorflow.GraphTransferConstNodeInfo")
	proto.RegisterType((*GraphTransferNodeInputInfo)(nil), "tensorflow.GraphTransferNodeInputInfo")
	proto.RegisterType((*GraphTransferNodeOutputInfo)(nil), "tensorflow.GraphTransferNodeOutputInfo")
	proto.RegisterType((*GraphTransferGraphInputNodeInfo)(nil), "tensorflow.GraphTransferGraphInputNodeInfo")
	proto.RegisterType((*GraphTransferGraphOutputNodeInfo)(nil), "tensorflow.GraphTransferGraphOutputNodeInfo")
	proto.RegisterType((*GraphTransferInfo)(nil), "tensorflow.GraphTransferInfo")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/graph_transfer_info.proto", fileDescriptor_c3a1e773f26c9475)
}

var fileDescriptor_c3a1e773f26c9475 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0x2e, 0xcd, 0xa4, 0x37, 0x4c, 0x5b, 0xa2, 0x56, 0xa8, 0xad, 0x11, 0x50, 0x2e,
	0x8d, 0xa5, 0xf6, 0x1d, 0xa9, 0x17, 0x54, 0x2a, 0xa4, 0x24, 0x2c, 0x7d, 0x40, 0x7d, 0xc0, 0xda,
	0xda, 0x6b, 0xd7, 0x82, 0xec, 0x5a, 0xf6, 0x46, 0x6d, 0xfa, 0x33, 0xfc, 0x1a, 0x9f, 0x81, 0xc4,
	0x0b, 0xda, 0x59, 0x37, 0x8e, 0x49, 0x9d, 0x22, 0x24, 0xde, 0xf6, 0x32, 0x73, 0xce, 0x9c, 0x99,
	0x63, 0x2f, 0xec, 0x4b, 0xc6, 0x53, 0x91, 0x04, 0xdf, 0xc4, 0x95, 0xe3, 0x89, 0x84, 0x39, 0x41,
	0x42, 0x07, 0xec, 0x4a, 0x24, 0x5f, 0x9d, 0x30, 0xa1, 0xf1, 0xa5, 0x2b, 0x13, 0xca, 0xd3, 0x80,
	0x25, 0x6e, 0xc4, 0x03, 0xd1, 0x89, 0x13, 0x21, 0x85, 0x05, 0x79, 0xd2, 0xfa, 0xb3, 0x72, 0x00,
	0x39, 0x8a, 0x59, 0xaa, 0x53, 0x6c, 0x02, 0x6b, 0x27, 0x0a, 0xef, 0x2c, 0x83, 0xeb, 0x0a, 0x9f,
	0x9d, 0xf2, 0x78, 0x28, 0xad, 0xc7, 0xd0, 0xe0, 0xc2, 0x67, 0x6e, 0xe4, 0xb7, 0x8d, 0x2d, 0x63,
	0xa7, 0x46, 0xea, 0x6a, 0x7b, 0xea, 0x5b, 0x9b, 0xd0, 0x12, 0x43, 0x19, 0x0f, 0xa5, 0x1b, 0x8b,
	0x44, 0xb6, 0x2b, 0x78, 0x09, 0xfa, 0xa8, 0x2f, 0x12, 0x69, 0xff, 0x30, 0x60, 0xf5, 0x0e, 0xd0,
	0x40, 0x58, 0x16, 0x54, 0x39, 0x1d, 0x30, 0x04, 0x6c, 0x12, 0x5c, 0x4f, 0xf2, 0x54, 0x0a, 0x3c,
	0x1b, 0xd0, 0x54, 0x95, 0xba, 0x98, 0x61, 0x62, 0xc6, 0x9c, 0x3a, 0xe8, 0xaa, 0xac, 0x75, 0x68,
	0xa6, 0xc2, 0x73, 0x45, 0xac, 0xf2, 0xaa, 0x98, 0xd7, 0x48, 0x85, 0xd7, 0x8b, 0x4f, 0x7d, 0xeb,
	0x09, 0x40, 0x4c, 0x7d, 0x3f, 0xe2, 0xa1, 0xba, 0xac, 0xe1, 0x65, 0x33, 0x3b, 0xd1, 0xf5, 0x47,
	0x4a, 0xa1, 0xeb, 0x89, 0x21, 0x97, 0xed, 0xba, 0xae, 0x1f, 0x8f, 0x8e, 0xd4, 0x89, 0xb5, 0x0d,
	0xf3, 0x99, 0x40, 0x1d, 0xd1, 0xc0, 0x88, 0x4c, 0x34, 0x86, 0xd8, 0xdf, 0x0d, 0x58, 0x2f, 0x48,
	0x3c, 0x12, 0x3c, 0x95, 0xff, 0xa6, 0x73, 0x05, 0x6a, 0xe9, 0x25, 0x8d, 0x95, 0x46, 0x73, 0xc7,
	0x24, 0x7a, 0xa3, 0x20, 0x7c, 0x2a, 0x29, 0x6a, 0x9b, 0x27, 0xb8, 0xb6, 0x5e, 0x41, 0xcd, 0x57,
	0x1d, 0x40, 0x4d, 0x8b, 0x7b, 0x2b, 0x9d, 0x7c, 0xc6, 0x9d, 0x63, 0x2a, 0xe9, 0xd9, 0x28, 0x66,
	0x44, 0x87, 0xd8, 0xd7, 0x7f, 0x14, 0x38, 0x1e, 0x2c, 0x16, 0x58, 0x3a, 0xdc, 0x03, 0x00, 0x7d,
	0xa1, 0x42, 0xdb, 0x95, 0x2d, 0x73, 0xa7, 0xb5, 0x67, 0x4f, 0xf2, 0xdc, 0x0d, 0x4a, 0x9a, 0xfc,
	0x76, 0x69, 0x9f, 0xc3, 0xc6, 0x54, 0x50, 0x0f, 0x7b, 0x37, 0x9b, 0xda, 0x86, 0x85, 0x01, 0xbd,
	0x76, 0x2f, 0x46, 0x92, 0xb9, 0x69, 0x74, 0xc3, 0x90, 0xbd, 0x46, 0x5a, 0x03, 0x7a, 0x7d, 0x38,
	0x92, 0xec, 0x53, 0x74, 0xc3, 0xec, 0x2b, 0xd8, 0x2c, 0x60, 0xe3, 0x06, 0x69, 0x67, 0xf6, 0x7e,
	0xdc, 0xe2, 0xca, 0x64, 0x8b, 0xc7, 0xed, 0x34, 0xff, 0xa6, 0x9d, 0x5b, 0xd3, 0xc4, 0x5a, 0xd5,
	0x7f, 0x66, 0xfe, 0x55, 0x85, 0x87, 0x05, 0x6a, 0xe4, 0x7a, 0x0b, 0xcd, 0x6c, 0x4e, 0x81, 0x68,
	0x1b, 0x38, 0xa6, 0xed, 0x7b, 0xc6, 0x14, 0x08, 0x32, 0xc7, 0x6f, 0x6b, 0xed, 0xc2, 0x92, 0xa7,
	0x2c, 0xeb, 0xe6, 0x28, 0x7a, 0xd8, 0xcf, 0x4b, 0x51, 0x0a, 0x16, 0x27, 0x0b, 0x5e, 0xc1, 0xf1,
	0x5d, 0x58, 0xca, 0x7d, 0xa3, 0xf1, 0xcc, 0x7b, 0xf0, 0x0a, 0x8e, 0x24, 0x0b, 0xbc, 0x60, 0xd0,
	0x8f, 0xb0, 0x8c, 0x78, 0xd9, 0x87, 0x88, 0x80, 0x55, 0x04, 0x7c, 0x31, 0x13, 0x30, 0x37, 0x1a,
	0x59, 0xe4, 0x45, 0xe3, 0x7d, 0x81, 0x55, 0xfd, 0xeb, 0xd4, 0x35, 0xe6, 0xc2, 0x6b, 0x88, 0xfb,
	0xba, 0x14, 0x77, 0xda, 0x64, 0xc4, 0x0a, 0xa7, 0x8d, 0x47, 0x61, 0x4d, 0xe3, 0x67, 0x35, 0xe7,
	0x04, 0x75, 0x24, 0x78, 0x33, 0x9b, 0xa0, 0x68, 0x26, 0xf2, 0x28, 0xbc, 0xc3, 0x61, 0x1f, 0xa0,
	0xe5, 0xb3, 0x54, 0x46, 0x9c, 0xca, 0x48, 0x70, 0xfc, 0x31, 0x2d, 0xee, 0xbd, 0x2c, 0xc5, 0x55,
	0x39, 0x9d, 0xe3, 0x3c, 0x81, 0x4c, 0x66, 0xdb, 0x4f, 0xa1, 0x35, 0x71, 0x67, 0x35, 0xc0, 0xec,
	0xf6, 0xfa, 0xcb, 0x0f, 0xac, 0x16, 0x34, 0xde, 0xbf, 0xfb, 0x7c, 0x70, 0xd2, 0xeb, 0x2e, 0x1b,
	0x87, 0x37, 0xd0, 0x16, 0x49, 0x38, 0xc9, 0x30, 0x7e, 0x47, 0x0e, 0xd7, 0xa6, 0xc8, 0xfa, 0xea,
	0x4d, 0xe9, 0x1b, 0xe7, 0x07, 0x61, 0x24, 0x2f, 0x87, 0x17, 0x1d, 0x4f, 0x0c, 0x1c, 0x29, 0x62,
	0x91, 0xee, 0xd2, 0xc8, 0xc9, 0x31, 0x76, 0xf1, 0xed, 0x71, 0x42, 0xe1, 0x94, 0x3e, 0x52, 0x3f,
	0x0d, 0xe3, 0xa2, 0x8e, 0x61, 0xfb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x56, 0xa2, 0x2f,
	0x0c, 0x07, 0x00, 0x00,
}
