// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/graph.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents the graph of operations
type GraphDef struct {
	Node []*NodeDef `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	// Compatibility versions of the graph.  See core/public/version.h for version
	// history.  The GraphDef version is distinct from the TensorFlow version, and
	// each release of TensorFlow will support a range of GraphDef versions.
	Versions *VersionDef `protobuf:"bytes,4,opt,name=versions,proto3" json:"versions,omitempty"`
	// Deprecated single version field; use versions above instead.  Since all
	// GraphDef changes before "versions" was introduced were forward
	// compatible, this field is entirely ignored.
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // Deprecated: Do not use.
	// EXPERIMENTAL. DO NOT USE OR DEPEND ON THIS YET.
	//
	// "library" provides user-defined functions.
	//
	// Naming:
	//   * library.function.name are in a flat namespace.
	//     NOTE: We may need to change it to be hierarchical to support
	//     different orgs. E.g.,
	//     { "/google/nn", { ... }},
	//     { "/google/vision", { ... }}
	//     { "/org_foo/module_bar", { ... }}
	//     map<string, FunctionDefLib> named_lib;
	//   * If node[i].op is the name of one function in "library",
	//     node[i] is deemed as a function call. Otherwise, node[i].op
	//     must be a primitive operation supported by the runtime.
	//
	//
	// Function call semantics:
	//
	//   * The callee may start execution as soon as some of its inputs
	//     are ready. The caller may want to use Tuple() mechanism to
	//     ensure all inputs are ready in the same time.
	//
	//   * The consumer of return values may start executing as soon as
	//     the return values the consumer depends on are ready.  The
	//     consumer may want to use Tuple() mechanism to ensure the
	//     consumer does not start until all return values of the callee
	//     function are ready.
	Library              *FunctionDefLibrary `protobuf:"bytes,2,opt,name=library,proto3" json:"library,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GraphDef) Reset()         { *m = GraphDef{} }
func (m *GraphDef) String() string { return proto.CompactTextString(m) }
func (*GraphDef) ProtoMessage()    {}
func (*GraphDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7b29295d3bc875a, []int{0}
}

func (m *GraphDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphDef.Unmarshal(m, b)
}
func (m *GraphDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphDef.Marshal(b, m, deterministic)
}
func (m *GraphDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDef.Merge(m, src)
}
func (m *GraphDef) XXX_Size() int {
	return xxx_messageInfo_GraphDef.Size(m)
}
func (m *GraphDef) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDef.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDef proto.InternalMessageInfo

func (m *GraphDef) GetNode() []*NodeDef {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GraphDef) GetVersions() *VersionDef {
	if m != nil {
		return m.Versions
	}
	return nil
}

// Deprecated: Do not use.
func (m *GraphDef) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GraphDef) GetLibrary() *FunctionDefLibrary {
	if m != nil {
		return m.Library
	}
	return nil
}

func init() {
	proto.RegisterType((*GraphDef)(nil), "tensorflow.GraphDef")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/graph.proto", fileDescriptor_c7b29295d3bc875a)
}

var fileDescriptor_c7b29295d3bc875a = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0x07, 0x70, 0xae, 0xad, 0xb6, 0x5c, 0xb7, 0x08, 0x72, 0x88, 0x48, 0x10, 0xc4, 0x2c, 0xcd,
	0x41, 0x5c, 0x5c, 0x0d, 0x41, 0x17, 0x91, 0x92, 0xc1, 0xc1, 0x45, 0xf2, 0xe3, 0x5d, 0x1a, 0x6c,
	0xf3, 0xc2, 0xbb, 0xab, 0xc5, 0xbf, 0xce, 0x7f, 0xcb, 0x51, 0x72, 0x69, 0x9a, 0x2c, 0xd5, 0x2d,
	0xe4, 0x3e, 0xef, 0x7b, 0xf7, 0x7d, 0xfc, 0xc6, 0x40, 0xa5, 0x91, 0xd4, 0x1a, 0x77, 0x32, 0x43,
	0x02, 0xa9, 0x28, 0xd9, 0xc0, 0x0e, 0xe9, 0x43, 0x16, 0x94, 0xd4, 0x2b, 0xbf, 0x26, 0x34, 0xe8,
	0xf0, 0x9e, 0x5d, 0x78, 0xc7, 0x47, 0x2a, 0xcc, 0xe1, 0x3d, 0x07, 0xd5, 0x4e, 0xfd, 0x25, 0xd5,
	0xb6, 0xca, 0x4c, 0x89, 0xd5, 0xff, 0xf2, 0x13, 0x48, 0x97, 0x58, 0xe9, 0x56, 0x5e, 0x7f, 0x33,
	0x3e, 0x7b, 0x6a, 0x5e, 0x16, 0x81, 0x72, 0x6e, 0xf9, 0xa4, 0xb9, 0x52, 0x30, 0x77, 0xec, 0xcd,
	0x83, 0x33, 0xbf, 0x4f, 0xf1, 0x5f, 0x30, 0x87, 0x08, 0x54, 0x6c, 0x81, 0x13, 0xf0, 0x59, 0x97,
	0x23, 0x26, 0x2e, 0xf3, 0xe6, 0xc1, 0xf9, 0x10, 0xbf, 0xb6, 0x67, 0x8d, 0x3f, 0x38, 0xe7, 0x92,
	0x4f, 0xf7, 0xdf, 0x62, 0xec, 0x32, 0xef, 0x24, 0x1c, 0x09, 0x16, 0x77, 0xbf, 0x9c, 0x7b, 0x3e,
	0x5d, 0x97, 0x29, 0x25, 0xf4, 0x25, 0x46, 0x36, 0xf0, 0x6a, 0x18, 0xf8, 0xb8, 0xaf, 0x17, 0x81,
	0x7a, 0x6e, 0x55, 0xdc, 0xf1, 0x10, 0xb9, 0x40, 0x2a, 0x86, 0xfa, 0x50, 0x36, 0x9c, 0xdb, 0x6a,
	0xcb, 0xa6, 0xa9, 0x5e, 0xb2, 0xb7, 0x87, 0xa2, 0x34, 0xab, 0x6d, 0xea, 0x67, 0xb8, 0x91, 0x06,
	0x6b, 0xd4, 0x8b, 0xa4, 0x94, 0xfd, 0xe0, 0xc2, 0xae, 0x44, 0x16, 0x28, 0x8f, 0xae, 0xef, 0x87,
	0xb1, 0xf4, 0xd4, 0xb2, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x0a, 0xe7, 0x0c, 0xec,
	0x01, 0x00, 0x00,
}
