// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/kernel_def.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KernelDef struct {
	// Must match the name of an Op.
	Op string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	// Type of device this kernel runs on.
	DeviceType string                      `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Constraint []*KernelDef_AttrConstraint `protobuf:"bytes,3,rep,name=constraint,proto3" json:"constraint,omitempty"`
	// Names of the Op's input_/output_args that reside in host memory
	// instead of device memory.
	HostMemoryArg []string `protobuf:"bytes,4,rep,name=host_memory_arg,json=hostMemoryArg,proto3" json:"host_memory_arg,omitempty"`
	// This allows experimental kernels to be registered for an op that
	// won't be used unless the user specifies a "_kernel" attr with
	// value matching this.
	Label string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	// Prioritization of kernel amongst different devices. By default we assume
	// priority is 0. The higher the priority the better. By default (i.e. if
	// this is not set), we prefer GPU kernels over CPU.
	Priority             int32    `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KernelDef) Reset()         { *m = KernelDef{} }
func (m *KernelDef) String() string { return proto.CompactTextString(m) }
func (*KernelDef) ProtoMessage()    {}
func (*KernelDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_18794e085ea7671a, []int{0}
}

func (m *KernelDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelDef.Unmarshal(m, b)
}
func (m *KernelDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelDef.Marshal(b, m, deterministic)
}
func (m *KernelDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelDef.Merge(m, src)
}
func (m *KernelDef) XXX_Size() int {
	return xxx_messageInfo_KernelDef.Size(m)
}
func (m *KernelDef) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelDef.DiscardUnknown(m)
}

var xxx_messageInfo_KernelDef proto.InternalMessageInfo

func (m *KernelDef) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *KernelDef) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *KernelDef) GetConstraint() []*KernelDef_AttrConstraint {
	if m != nil {
		return m.Constraint
	}
	return nil
}

func (m *KernelDef) GetHostMemoryArg() []string {
	if m != nil {
		return m.HostMemoryArg
	}
	return nil
}

func (m *KernelDef) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *KernelDef) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type KernelDef_AttrConstraint struct {
	// Name of an attr from the Op.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A list of values that this kernel supports for this attr.
	// Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
	AllowedValues        *AttrValue `protobuf:"bytes,2,opt,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KernelDef_AttrConstraint) Reset()         { *m = KernelDef_AttrConstraint{} }
func (m *KernelDef_AttrConstraint) String() string { return proto.CompactTextString(m) }
func (*KernelDef_AttrConstraint) ProtoMessage()    {}
func (*KernelDef_AttrConstraint) Descriptor() ([]byte, []int) {
	return fileDescriptor_18794e085ea7671a, []int{0, 0}
}

func (m *KernelDef_AttrConstraint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelDef_AttrConstraint.Unmarshal(m, b)
}
func (m *KernelDef_AttrConstraint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelDef_AttrConstraint.Marshal(b, m, deterministic)
}
func (m *KernelDef_AttrConstraint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelDef_AttrConstraint.Merge(m, src)
}
func (m *KernelDef_AttrConstraint) XXX_Size() int {
	return xxx_messageInfo_KernelDef_AttrConstraint.Size(m)
}
func (m *KernelDef_AttrConstraint) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelDef_AttrConstraint.DiscardUnknown(m)
}

var xxx_messageInfo_KernelDef_AttrConstraint proto.InternalMessageInfo

func (m *KernelDef_AttrConstraint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KernelDef_AttrConstraint) GetAllowedValues() *AttrValue {
	if m != nil {
		return m.AllowedValues
	}
	return nil
}

// A collection of KernelDefs
type KernelList struct {
	Kernel               []*KernelDef `protobuf:"bytes,1,rep,name=kernel,proto3" json:"kernel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KernelList) Reset()         { *m = KernelList{} }
func (m *KernelList) String() string { return proto.CompactTextString(m) }
func (*KernelList) ProtoMessage()    {}
func (*KernelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_18794e085ea7671a, []int{1}
}

func (m *KernelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelList.Unmarshal(m, b)
}
func (m *KernelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelList.Marshal(b, m, deterministic)
}
func (m *KernelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelList.Merge(m, src)
}
func (m *KernelList) XXX_Size() int {
	return xxx_messageInfo_KernelList.Size(m)
}
func (m *KernelList) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelList.DiscardUnknown(m)
}

var xxx_messageInfo_KernelList proto.InternalMessageInfo

func (m *KernelList) GetKernel() []*KernelDef {
	if m != nil {
		return m.Kernel
	}
	return nil
}

func init() {
	proto.RegisterType((*KernelDef)(nil), "tensorflow.KernelDef")
	proto.RegisterType((*KernelDef_AttrConstraint)(nil), "tensorflow.KernelDef.AttrConstraint")
	proto.RegisterType((*KernelList)(nil), "tensorflow.KernelList")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/kernel_def.proto", fileDescriptor_18794e085ea7671a)
}

var fileDescriptor_18794e085ea7671a = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0xab, 0xda, 0x40,
	0x14, 0xc5, 0x49, 0xfc, 0x43, 0xbd, 0xa2, 0xc2, 0x50, 0x61, 0x70, 0xd3, 0x20, 0xa5, 0x84, 0x82,
	0x09, 0xd8, 0x65, 0xbb, 0xd1, 0xba, 0x6b, 0x0b, 0x12, 0x4a, 0x17, 0xdd, 0x84, 0x49, 0xbc, 0x89,
	0xc1, 0x24, 0x37, 0xcc, 0x8c, 0x4a, 0xbe, 0x5d, 0x3f, 0x56, 0x97, 0x8f, 0x4c, 0x24, 0xfa, 0xe0,
	0xbd, 0xb7, 0xcb, 0xbd, 0xf3, 0x3b, 0x77, 0x72, 0xee, 0x19, 0xf8, 0xac, 0xb1, 0x54, 0x24, 0x93,
	0x9c, 0xae, 0x7e, 0x4c, 0x12, 0xfd, 0x44, 0x8a, 0x02, 0xaf, 0x24, 0x4f, 0xfe, 0x09, 0x65, 0x89,
	0x79, 0x78, 0xc0, 0xc4, 0xab, 0x24, 0x69, 0x62, 0x70, 0x67, 0x17, 0x6f, 0xe8, 0x84, 0xd6, 0x32,
	0xbc, 0x88, 0xfc, 0x8c, 0xad, 0x6e, 0xf9, 0xcf, 0x86, 0xd1, 0x0f, 0x33, 0x6c, 0x87, 0x09, 0x9b,
	0x82, 0x4d, 0x15, 0xb7, 0x1c, 0xcb, 0x1d, 0x05, 0x36, 0x55, 0xec, 0x03, 0x8c, 0x0f, 0x78, 0xc9,
	0x62, 0x0c, 0x75, 0x5d, 0x21, 0xb7, 0xcd, 0x01, 0xb4, 0xad, 0xdf, 0x75, 0x85, 0x6c, 0x07, 0x10,
	0x53, 0xa9, 0xb4, 0x14, 0x59, 0xa9, 0x79, 0xcf, 0xe9, 0xb9, 0xe3, 0xf5, 0x47, 0xef, 0x7e, 0xbf,
	0xd7, 0xcd, 0xf6, 0x36, 0x5a, 0xcb, 0xef, 0x1d, 0x1b, 0x3c, 0xe8, 0xd8, 0x27, 0x98, 0x1d, 0x49,
	0xe9, 0xb0, 0xc0, 0x82, 0x64, 0x1d, 0x0a, 0x99, 0xf2, 0xbe, 0xd3, 0x73, 0x47, 0xc1, 0xa4, 0x69,
	0xff, 0x32, 0xdd, 0x8d, 0x4c, 0xd9, 0x7b, 0x18, 0xe4, 0x22, 0xc2, 0x9c, 0x0f, 0xcc, 0x8f, 0xb4,
	0x05, 0x5b, 0xc0, 0xbb, 0x4a, 0x66, 0x24, 0x33, 0x5d, 0xf3, 0xa1, 0x63, 0xb9, 0x83, 0xa0, 0xab,
	0x17, 0x11, 0x4c, 0x9f, 0xdf, 0xcb, 0x18, 0xf4, 0x4b, 0x51, 0xe0, 0xcd, 0xa4, 0xf9, 0x66, 0xdf,
	0x60, 0x2a, 0xf2, 0x9c, 0xae, 0x78, 0x68, 0x77, 0xa3, 0x8c, 0xd3, 0xf1, 0x7a, 0xfe, 0xe8, 0xa4,
	0x99, 0xf3, 0xa7, 0x39, 0x0d, 0x26, 0x37, 0xd8, 0x54, 0x6a, 0xf9, 0x15, 0xa0, 0x75, 0xf9, 0x33,
	0x53, 0x9a, 0xad, 0x60, 0xd8, 0x86, 0xc3, 0x2d, 0xb3, 0x8d, 0xf9, 0x8b, 0xdb, 0x08, 0x6e, 0xd0,
	0x56, 0x01, 0x27, 0x99, 0x3e, 0x32, 0x5d, 0x58, 0xdb, 0x59, 0x87, 0xef, 0x9b, 0xac, 0xd4, 0xde,
	0xfa, 0xbb, 0x49, 0x33, 0x7d, 0x3c, 0x47, 0x5e, 0x4c, 0x85, 0xaf, 0xa9, 0x22, 0xb5, 0x12, 0x99,
	0x7f, 0x17, 0xaf, 0x4c, 0xa8, 0x7e, 0x4a, 0xfe, 0xab, 0x4f, 0xe0, 0xbf, 0x65, 0x45, 0x43, 0x83,
	0x7d, 0x79, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x33, 0x98, 0xef, 0x61, 0x02, 0x00, 0x00,
}
