// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/node_def.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeDef struct {
	// The name given to this operator. Used for naming inputs,
	// logging, visualization, etc.  Unique within a single GraphDef.
	// Must match the regexp "[A-Za-z0-9.][A-Za-z0-9_>./]*".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The operation name.  There may be custom parameters in attrs.
	// Op names starting with an underscore are reserved for internal use.
	Op string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	// Each input is "node:src_output" with "node" being a string name and
	// "src_output" indicating which output tensor to use from "node". If
	// "src_output" is 0 the ":0" suffix can be omitted.  Regular inputs
	// may optionally be followed by control inputs that have the format
	// "^node".
	Input []string `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`
	// A (possibly partial) specification for the device on which this
	// node should be placed.
	// The expected syntax for this string is as follows:
	//
	// DEVICE_SPEC ::= PARTIAL_SPEC
	//
	// PARTIAL_SPEC ::= ("/" CONSTRAINT) *
	// CONSTRAINT ::= ("job:" JOB_NAME)
	//              | ("replica:" [1-9][0-9]*)
	//              | ("task:" [1-9][0-9]*)
	//              | ("device:" [A-Za-z]* ":" ([1-9][0-9]* | "*") )
	//
	// Valid values for this string include:
	// * "/job:worker/replica:0/task:1/device:GPU:3"  (full specification)
	// * "/job:worker/device:GPU:3"                   (partial specification)
	// * ""                                    (no specification)
	//
	// If the constraints do not resolve to a single device (or if this
	// field is empty or not present), the runtime will attempt to
	// choose a device automatically.
	Device string `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	// Operation-specific graph-construction-time configuration.
	// Note that this should include all attrs defined in the
	// corresponding OpDef, including those with a value matching
	// the default -- this allows the default to change and makes
	// NodeDefs easier to interpret on their own.  However, if
	// an attr with a default is not specified in this list, the
	// default will be used.
	// The "names" (keys) must match the regexp "[a-z][a-z0-9_]+" (and
	// one of the names from the corresponding OpDef's attr field).
	// The values must have a type matching the corresponding OpDef
	// attr's type field.
	// TODO(josh11b): Add some examples here showing best practices.
	Attr map[string]*AttrValue `protobuf:"bytes,5,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// This stores debug information associated with the node.
	ExperimentalDebugInfo *NodeDef_ExperimentalDebugInfo `protobuf:"bytes,6,opt,name=experimental_debug_info,json=experimentalDebugInfo,proto3" json:"experimental_debug_info,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                       `json:"-"`
	XXX_unrecognized      []byte                         `json:"-"`
	XXX_sizecache         int32                          `json:"-"`
}

func (m *NodeDef) Reset()         { *m = NodeDef{} }
func (m *NodeDef) String() string { return proto.CompactTextString(m) }
func (*NodeDef) ProtoMessage()    {}
func (*NodeDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34b3b836a96140b, []int{0}
}

func (m *NodeDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDef.Unmarshal(m, b)
}
func (m *NodeDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDef.Marshal(b, m, deterministic)
}
func (m *NodeDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDef.Merge(m, src)
}
func (m *NodeDef) XXX_Size() int {
	return xxx_messageInfo_NodeDef.Size(m)
}
func (m *NodeDef) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDef.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDef proto.InternalMessageInfo

func (m *NodeDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeDef) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *NodeDef) GetInput() []string {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *NodeDef) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *NodeDef) GetAttr() map[string]*AttrValue {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *NodeDef) GetExperimentalDebugInfo() *NodeDef_ExperimentalDebugInfo {
	if m != nil {
		return m.ExperimentalDebugInfo
	}
	return nil
}

type NodeDef_ExperimentalDebugInfo struct {
	// Opaque string inserted into error messages created by the runtime.
	//
	// This is intended to store the list of names of the nodes from the
	// original graph that this node was derived. For example if this node, say
	// C, was result of a fusion of 2 nodes A and B, then 'original_node' would
	// be {A, B}. This information can be used to map errors originating at the
	// current node to some top level source code.
	OriginalNodeNames []string `protobuf:"bytes,1,rep,name=original_node_names,json=originalNodeNames,proto3" json:"original_node_names,omitempty"`
	// This is intended to store the list of names of the functions from the
	// original graph that this node was derived. For example if this node, say
	// C, was result of a fusion of node A in function FA and node B in function
	// FB, then `original_funcs` would be {FA, FB}. If the node is in the top
	// level graph, the `original_func` is empty. This information, with the
	// `original_node_names` can be used to map errors originating at the
	// current ndoe to some top level source code.
	OriginalFuncNames    []string `protobuf:"bytes,2,rep,name=original_func_names,json=originalFuncNames,proto3" json:"original_func_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDef_ExperimentalDebugInfo) Reset()         { *m = NodeDef_ExperimentalDebugInfo{} }
func (m *NodeDef_ExperimentalDebugInfo) String() string { return proto.CompactTextString(m) }
func (*NodeDef_ExperimentalDebugInfo) ProtoMessage()    {}
func (*NodeDef_ExperimentalDebugInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b34b3b836a96140b, []int{0, 1}
}

func (m *NodeDef_ExperimentalDebugInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDef_ExperimentalDebugInfo.Unmarshal(m, b)
}
func (m *NodeDef_ExperimentalDebugInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDef_ExperimentalDebugInfo.Marshal(b, m, deterministic)
}
func (m *NodeDef_ExperimentalDebugInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDef_ExperimentalDebugInfo.Merge(m, src)
}
func (m *NodeDef_ExperimentalDebugInfo) XXX_Size() int {
	return xxx_messageInfo_NodeDef_ExperimentalDebugInfo.Size(m)
}
func (m *NodeDef_ExperimentalDebugInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDef_ExperimentalDebugInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDef_ExperimentalDebugInfo proto.InternalMessageInfo

func (m *NodeDef_ExperimentalDebugInfo) GetOriginalNodeNames() []string {
	if m != nil {
		return m.OriginalNodeNames
	}
	return nil
}

func (m *NodeDef_ExperimentalDebugInfo) GetOriginalFuncNames() []string {
	if m != nil {
		return m.OriginalFuncNames
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeDef)(nil), "tensorflow.NodeDef")
	proto.RegisterMapType((map[string]*AttrValue)(nil), "tensorflow.NodeDef.AttrEntry")
	proto.RegisterType((*NodeDef_ExperimentalDebugInfo)(nil), "tensorflow.NodeDef.ExperimentalDebugInfo")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/node_def.proto", fileDescriptor_b34b3b836a96140b)
}

var fileDescriptor_b34b3b836a96140b = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x86, 0x99, 0xa4, 0xad, 0x64, 0x0a, 0xa2, 0xa3, 0xd5, 0xa1, 0x20, 0x04, 0x57, 0x51, 0xb9,
	0x09, 0xd6, 0x8d, 0xb8, 0xbb, 0x97, 0x5b, 0xc1, 0x4d, 0x29, 0x59, 0xb8, 0x70, 0x13, 0xa6, 0xc9,
	0x49, 0x1c, 0x9a, 0xcc, 0x09, 0xd3, 0x49, 0x6b, 0xff, 0x9a, 0xbf, 0xcc, 0xa5, 0xcc, 0x34, 0xb7,
	0x1f, 0xd0, 0xee, 0x66, 0xe6, 0x3c, 0xef, 0xbc, 0xe7, 0x8b, 0x46, 0x06, 0xd4, 0x06, 0x75, 0x59,
	0xe3, 0x2e, 0xc9, 0x51, 0x43, 0x52, 0x6a, 0xd1, 0xc0, 0x0e, 0xf5, 0x3a, 0x51, 0x58, 0x40, 0x56,
	0x40, 0x19, 0xb7, 0x1a, 0x0d, 0x32, 0x7a, 0x22, 0xa7, 0x1f, 0x6f, 0xab, 0x84, 0x31, 0x3a, 0xdb,
	0x8a, 0xba, 0x83, 0x83, 0xee, 0xfd, 0x5f, 0x9f, 0x3e, 0x5b, 0x60, 0x01, 0x8f, 0x50, 0x32, 0x46,
	0x07, 0x4a, 0x34, 0xc0, 0x49, 0x48, 0xa2, 0x20, 0x75, 0x67, 0xf6, 0x9c, 0x7a, 0xd8, 0x72, 0xcf,
	0xbd, 0x78, 0xd8, 0xb2, 0xd7, 0x74, 0x28, 0x55, 0xdb, 0x19, 0xee, 0x87, 0x7e, 0x14, 0xa4, 0x87,
	0x0b, 0x7b, 0x43, 0x47, 0x05, 0x6c, 0x65, 0x0e, 0x7c, 0xe0, 0xc8, 0xfe, 0xc6, 0x3e, 0xd3, 0x81,
	0x75, 0xe4, 0xc3, 0xd0, 0x8f, 0xc6, 0xb3, 0x77, 0xf1, 0x29, 0xb1, 0xb8, 0x37, 0x8d, 0xef, 0x8d,
	0xd1, 0x73, 0x65, 0xf4, 0x3e, 0x75, 0x28, 0x13, 0xf4, 0x2d, 0xfc, 0x69, 0x41, 0xcb, 0x06, 0x94,
	0x11, 0x75, 0x56, 0xc0, 0xaa, 0xab, 0x32, 0xa9, 0x4a, 0xe4, 0xa3, 0x90, 0x44, 0xe3, 0xd9, 0x87,
	0x6b, 0xbf, 0xcc, 0xcf, 0x24, 0x8f, 0x56, 0xf1, 0x43, 0x95, 0x98, 0x4e, 0xe0, 0xda, 0xf3, 0x74,
	0x41, 0x83, 0xa3, 0x2b, 0x7b, 0x41, 0xfd, 0x35, 0xec, 0xfb, 0x9a, 0xed, 0x91, 0x7d, 0xa2, 0x43,
	0xd7, 0x21, 0x57, 0xf5, 0x78, 0x36, 0x39, 0xf7, 0xb3, 0xba, 0x9f, 0x36, 0x98, 0x1e, 0x98, 0x6f,
	0xde, 0x57, 0x32, 0xdd, 0xd1, 0xc9, 0x55, 0x7f, 0x16, 0xd3, 0x57, 0xa8, 0x65, 0x25, 0x95, 0xa8,
	0x33, 0x37, 0x2f, 0xdb, 0xd2, 0x0d, 0x27, 0xae, 0x75, 0x2f, 0x9f, 0x42, 0xb6, 0x86, 0x85, 0x0d,
	0x5c, 0xf0, 0x65, 0xa7, 0xf2, 0x9e, 0xf7, 0x2e, 0xf9, 0xef, 0x9d, 0xca, 0x1d, 0xff, 0xd0, 0x50,
	0x8e, 0xba, 0x3a, 0xcf, 0xef, 0x38, 0xe9, 0x87, 0xc0, 0x7e, 0xbb, 0xb4, 0x33, 0x5e, 0x92, 0x5f,
	0xf7, 0x95, 0x34, 0xbf, 0xbb, 0x55, 0x9c, 0x63, 0x93, 0x18, 0x6c, 0x71, 0x73, 0x27, 0x64, 0x72,
	0x92, 0xdd, 0xb9, 0x5d, 0x48, 0x2a, 0x4c, 0x6e, 0x6e, 0xce, 0x3f, 0x42, 0x56, 0x23, 0x87, 0x7d,
	0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x07, 0x37, 0xb9, 0x96, 0x02, 0x00, 0x00,
}
