// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/example/example_parser_configuration.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	framework "github.com/topos-ai/tensorflow-proto/go/tensorflow/core/framework"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VarLenFeatureProto struct {
	Dtype                   framework.DataType `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	ValuesOutputTensorName  string             `protobuf:"bytes,2,opt,name=values_output_tensor_name,json=valuesOutputTensorName,proto3" json:"values_output_tensor_name,omitempty"`
	IndicesOutputTensorName string             `protobuf:"bytes,3,opt,name=indices_output_tensor_name,json=indicesOutputTensorName,proto3" json:"indices_output_tensor_name,omitempty"`
	ShapesOutputTensorName  string             `protobuf:"bytes,4,opt,name=shapes_output_tensor_name,json=shapesOutputTensorName,proto3" json:"shapes_output_tensor_name,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}           `json:"-"`
	XXX_unrecognized        []byte             `json:"-"`
	XXX_sizecache           int32              `json:"-"`
}

func (m *VarLenFeatureProto) Reset()         { *m = VarLenFeatureProto{} }
func (m *VarLenFeatureProto) String() string { return proto.CompactTextString(m) }
func (*VarLenFeatureProto) ProtoMessage()    {}
func (*VarLenFeatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ac05576ebb1f2e, []int{0}
}

func (m *VarLenFeatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VarLenFeatureProto.Unmarshal(m, b)
}
func (m *VarLenFeatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VarLenFeatureProto.Marshal(b, m, deterministic)
}
func (m *VarLenFeatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VarLenFeatureProto.Merge(m, src)
}
func (m *VarLenFeatureProto) XXX_Size() int {
	return xxx_messageInfo_VarLenFeatureProto.Size(m)
}
func (m *VarLenFeatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VarLenFeatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_VarLenFeatureProto proto.InternalMessageInfo

func (m *VarLenFeatureProto) GetDtype() framework.DataType {
	if m != nil {
		return m.Dtype
	}
	return framework.DataType_DT_INVALID
}

func (m *VarLenFeatureProto) GetValuesOutputTensorName() string {
	if m != nil {
		return m.ValuesOutputTensorName
	}
	return ""
}

func (m *VarLenFeatureProto) GetIndicesOutputTensorName() string {
	if m != nil {
		return m.IndicesOutputTensorName
	}
	return ""
}

func (m *VarLenFeatureProto) GetShapesOutputTensorName() string {
	if m != nil {
		return m.ShapesOutputTensorName
	}
	return ""
}

type FixedLenFeatureProto struct {
	Dtype                  framework.DataType          `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	Shape                  *framework.TensorShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	DefaultValue           *framework.TensorProto      `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	ValuesOutputTensorName string                      `protobuf:"bytes,4,opt,name=values_output_tensor_name,json=valuesOutputTensorName,proto3" json:"values_output_tensor_name,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                    `json:"-"`
	XXX_unrecognized       []byte                      `json:"-"`
	XXX_sizecache          int32                       `json:"-"`
}

func (m *FixedLenFeatureProto) Reset()         { *m = FixedLenFeatureProto{} }
func (m *FixedLenFeatureProto) String() string { return proto.CompactTextString(m) }
func (*FixedLenFeatureProto) ProtoMessage()    {}
func (*FixedLenFeatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ac05576ebb1f2e, []int{1}
}

func (m *FixedLenFeatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedLenFeatureProto.Unmarshal(m, b)
}
func (m *FixedLenFeatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedLenFeatureProto.Marshal(b, m, deterministic)
}
func (m *FixedLenFeatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedLenFeatureProto.Merge(m, src)
}
func (m *FixedLenFeatureProto) XXX_Size() int {
	return xxx_messageInfo_FixedLenFeatureProto.Size(m)
}
func (m *FixedLenFeatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedLenFeatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_FixedLenFeatureProto proto.InternalMessageInfo

func (m *FixedLenFeatureProto) GetDtype() framework.DataType {
	if m != nil {
		return m.Dtype
	}
	return framework.DataType_DT_INVALID
}

func (m *FixedLenFeatureProto) GetShape() *framework.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *FixedLenFeatureProto) GetDefaultValue() *framework.TensorProto {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *FixedLenFeatureProto) GetValuesOutputTensorName() string {
	if m != nil {
		return m.ValuesOutputTensorName
	}
	return ""
}

type FeatureConfiguration struct {
	// Types that are valid to be assigned to Config:
	//	*FeatureConfiguration_FixedLenFeature
	//	*FeatureConfiguration_VarLenFeature
	Config               isFeatureConfiguration_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FeatureConfiguration) Reset()         { *m = FeatureConfiguration{} }
func (m *FeatureConfiguration) String() string { return proto.CompactTextString(m) }
func (*FeatureConfiguration) ProtoMessage()    {}
func (*FeatureConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ac05576ebb1f2e, []int{2}
}

func (m *FeatureConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureConfiguration.Unmarshal(m, b)
}
func (m *FeatureConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureConfiguration.Marshal(b, m, deterministic)
}
func (m *FeatureConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureConfiguration.Merge(m, src)
}
func (m *FeatureConfiguration) XXX_Size() int {
	return xxx_messageInfo_FeatureConfiguration.Size(m)
}
func (m *FeatureConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureConfiguration proto.InternalMessageInfo

type isFeatureConfiguration_Config interface {
	isFeatureConfiguration_Config()
}

type FeatureConfiguration_FixedLenFeature struct {
	FixedLenFeature *FixedLenFeatureProto `protobuf:"bytes,1,opt,name=fixed_len_feature,json=fixedLenFeature,proto3,oneof"`
}

type FeatureConfiguration_VarLenFeature struct {
	VarLenFeature *VarLenFeatureProto `protobuf:"bytes,2,opt,name=var_len_feature,json=varLenFeature,proto3,oneof"`
}

func (*FeatureConfiguration_FixedLenFeature) isFeatureConfiguration_Config() {}

func (*FeatureConfiguration_VarLenFeature) isFeatureConfiguration_Config() {}

func (m *FeatureConfiguration) GetConfig() isFeatureConfiguration_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *FeatureConfiguration) GetFixedLenFeature() *FixedLenFeatureProto {
	if x, ok := m.GetConfig().(*FeatureConfiguration_FixedLenFeature); ok {
		return x.FixedLenFeature
	}
	return nil
}

func (m *FeatureConfiguration) GetVarLenFeature() *VarLenFeatureProto {
	if x, ok := m.GetConfig().(*FeatureConfiguration_VarLenFeature); ok {
		return x.VarLenFeature
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FeatureConfiguration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FeatureConfiguration_FixedLenFeature)(nil),
		(*FeatureConfiguration_VarLenFeature)(nil),
	}
}

type ExampleParserConfiguration struct {
	FeatureMap           map[string]*FeatureConfiguration `protobuf:"bytes,1,rep,name=feature_map,json=featureMap,proto3" json:"feature_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ExampleParserConfiguration) Reset()         { *m = ExampleParserConfiguration{} }
func (m *ExampleParserConfiguration) String() string { return proto.CompactTextString(m) }
func (*ExampleParserConfiguration) ProtoMessage()    {}
func (*ExampleParserConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ac05576ebb1f2e, []int{3}
}

func (m *ExampleParserConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleParserConfiguration.Unmarshal(m, b)
}
func (m *ExampleParserConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleParserConfiguration.Marshal(b, m, deterministic)
}
func (m *ExampleParserConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleParserConfiguration.Merge(m, src)
}
func (m *ExampleParserConfiguration) XXX_Size() int {
	return xxx_messageInfo_ExampleParserConfiguration.Size(m)
}
func (m *ExampleParserConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleParserConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleParserConfiguration proto.InternalMessageInfo

func (m *ExampleParserConfiguration) GetFeatureMap() map[string]*FeatureConfiguration {
	if m != nil {
		return m.FeatureMap
	}
	return nil
}

func init() {
	proto.RegisterType((*VarLenFeatureProto)(nil), "tensorflow.VarLenFeatureProto")
	proto.RegisterType((*FixedLenFeatureProto)(nil), "tensorflow.FixedLenFeatureProto")
	proto.RegisterType((*FeatureConfiguration)(nil), "tensorflow.FeatureConfiguration")
	proto.RegisterType((*ExampleParserConfiguration)(nil), "tensorflow.ExampleParserConfiguration")
	proto.RegisterMapType((map[string]*FeatureConfiguration)(nil), "tensorflow.ExampleParserConfiguration.FeatureMapEntry")
}

func init() {
	proto.RegisterFile("tensorflow/core/example/example_parser_configuration.proto", fileDescriptor_80ac05576ebb1f2e)
}

var fileDescriptor_80ac05576ebb1f2e = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe7, 0x76, 0x9d, 0xd8, 0x1b, 0x46, 0x21, 0x9a, 0xb6, 0x2e, 0x42, 0x28, 0xaa, 0x04,
	0xaa, 0x10, 0x4b, 0xa4, 0x20, 0x4d, 0x6c, 0x20, 0x21, 0x15, 0x36, 0xf5, 0x00, 0xa3, 0x0a, 0xd3,
	0x90, 0xb8, 0x58, 0x5e, 0xeb, 0x74, 0xd1, 0x92, 0xd8, 0x72, 0x9c, 0x6e, 0xbd, 0xf1, 0xb9, 0xf8,
	0x20, 0x7c, 0x0d, 0x0e, 0x5c, 0x38, 0xa2, 0xd8, 0x51, 0x9b, 0xb6, 0x69, 0x39, 0xec, 0xd4, 0xca,
	0xef, 0xef, 0x79, 0xff, 0x3c, 0xf1, 0x6b, 0x38, 0x91, 0x34, 0x49, 0x99, 0x08, 0x22, 0x76, 0xeb,
	0x0e, 0x98, 0xa0, 0x2e, 0xbd, 0x23, 0x31, 0x8f, 0xa6, 0xbf, 0x98, 0x13, 0x91, 0x52, 0x81, 0x07,
	0x2c, 0x09, 0xc2, 0x51, 0x26, 0x88, 0x0c, 0x59, 0xe2, 0x70, 0xc1, 0x24, 0x33, 0x61, 0xa6, 0xb5,
	0x5e, 0x2d, 0xe6, 0x09, 0x04, 0x89, 0xe9, 0x2d, 0x13, 0x37, 0xae, 0x8e, 0xe0, 0xf4, 0x9a, 0x70,
	0xaa, 0x95, 0xd6, 0x8b, 0xff, 0xd1, 0x05, 0xf7, 0x7c, 0x0d, 0x37, 0xe1, 0x34, 0xd5, 0x58, 0xfb,
	0x0f, 0x02, 0xf3, 0x92, 0x88, 0x4f, 0x34, 0x39, 0xa3, 0x44, 0x66, 0x82, 0xf6, 0x55, 0x7f, 0x2f,
	0xa1, 0x31, 0xcc, 0xb1, 0x16, 0xb2, 0x51, 0xe7, 0x91, 0xb7, 0xeb, 0xcc, 0xb2, 0x39, 0x1f, 0x89,
	0x24, 0x17, 0x13, 0x4e, 0x7d, 0x8d, 0x98, 0xc7, 0x70, 0x30, 0x26, 0x51, 0x46, 0x53, 0xcc, 0x32,
	0xc9, 0x33, 0x89, 0x8b, 0xae, 0x13, 0x12, 0xd3, 0x56, 0xcd, 0x46, 0x9d, 0x6d, 0x7f, 0x4f, 0x03,
	0x5f, 0x54, 0xfc, 0x42, 0x85, 0xcf, 0x49, 0x4c, 0xcd, 0xb7, 0x60, 0x85, 0xc9, 0x30, 0x1c, 0x54,
	0x6b, 0xeb, 0x4a, 0xbb, 0x5f, 0x10, 0x4b, 0xe2, 0x63, 0x38, 0x50, 0xc6, 0x54, 0x6a, 0x37, 0x75,
	0x5d, 0x0d, 0x2c, 0x4a, 0xdb, 0xbf, 0x11, 0xec, 0x9e, 0x85, 0x77, 0x74, 0x78, 0x9f, 0xb9, 0x3d,
	0x68, 0xa8, 0xf4, 0x6a, 0x46, 0xc3, 0x7b, 0x5a, 0x66, 0x75, 0xad, 0xaf, 0x79, 0x58, 0x25, 0xf6,
	0x35, 0x6a, 0xbe, 0x83, 0x9d, 0x21, 0x0d, 0x48, 0x16, 0x49, 0xac, 0x2c, 0x51, 0x33, 0x1a, 0xde,
	0xfe, 0xb2, 0x56, 0xcb, 0x1e, 0x16, 0xf4, 0x65, 0x0e, 0xaf, 0x77, 0x7a, 0x73, 0x9d, 0xd3, 0xed,
	0x9f, 0xf9, 0xc4, 0x7a, 0xd2, 0x0f, 0xe5, 0xfb, 0x68, 0x9e, 0xc3, 0x93, 0x20, 0x77, 0x02, 0x47,
	0x34, 0xc1, 0x81, 0x26, 0xd4, 0xf4, 0x86, 0x67, 0x97, 0xbb, 0xaa, 0xb2, 0xab, 0xb7, 0xe1, 0x37,
	0x83, 0xf9, 0x73, 0xb3, 0x07, 0xcd, 0x31, 0x11, 0x73, 0xd9, 0xb4, 0x3f, 0xcf, 0xca, 0xd9, 0x96,
	0xaf, 0x5c, 0x6f, 0xc3, 0xdf, 0x19, 0x97, 0x4f, 0xbb, 0x0f, 0x60, 0x4b, 0xaf, 0x4e, 0xfb, 0x17,
	0x02, 0xeb, 0x54, 0x2f, 0x55, 0x5f, 0xed, 0xd4, 0xfc, 0x08, 0xdf, 0xc0, 0x28, 0x4a, 0xe1, 0x98,
	0xf0, 0x16, 0xb2, 0xeb, 0x1d, 0xc3, 0x3b, 0x2a, 0x97, 0x5b, 0x2d, 0x76, 0x8a, 0x6a, 0x9f, 0x09,
	0x3f, 0x4d, 0xa4, 0x98, 0xf8, 0x10, 0x4c, 0x0f, 0x2c, 0x0c, 0xcd, 0x85, 0xb0, 0xf9, 0x18, 0xea,
	0x37, 0x74, 0xa2, 0x0c, 0xda, 0xf6, 0xf3, 0xbf, 0xe6, 0x11, 0x34, 0xf4, 0xa7, 0xac, 0x55, 0x98,
	0x56, 0xe1, 0xb8, 0xaf, 0xf1, 0x93, 0xda, 0x1b, 0xd4, 0xfd, 0x81, 0x60, 0x8f, 0x89, 0x51, 0x59,
	0x52, 0x3c, 0x1e, 0x5d, 0x7b, 0x75, 0xcf, 0xca, 0xaf, 0xb4, 0x8f, 0xbe, 0xbf, 0x1f, 0x85, 0xf2,
	0x3a, 0xbb, 0x72, 0x06, 0x2c, 0x76, 0x25, 0xe3, 0x2c, 0x3d, 0x24, 0xa1, 0x3b, 0xcb, 0x75, 0xa8,
	0x56, 0xdc, 0x1d, 0x31, 0x77, 0xc5, 0x4b, 0xf5, 0x17, 0xa1, 0xab, 0x2d, 0x05, 0xbd, 0xfe, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x2b, 0x4c, 0xe1, 0xa8, 0xce, 0x04, 0x00, 0x00,
}
